### ISSUE TITLE
电源只加载了4项

### ISSUE THREAD

**Issue by CrazyDoraemon** [skybrim/Gigabyte-B85N-Phoenix-WiFi#1]
主板：技嘉 B85N Phoenix-WIFI v2.0
CPU：E3-1231 V3
显卡：蓝宝石RX560D 4G D5 白金版 OC 75W(已刷560)
内存：金士顿骇客神条 DDR3 1600 16GB(8GBx2)
硬盘：mSATA SSD
无线网卡：BCM94352HMB 蓝牙4.0
-------------------------------------------------------
机型iMacPro1,1节能里电源只加载了4项，
加入SSDT-LPC.aml后可以加载5项。
另外USB没有定制哦，用的还是USBInjectAll.kext

**Comment by skybrim** [comment]
嗯，没有太仔细打磨。
打算对标 iMac2019 升级下电脑，无 T2 芯片应该比较容易仿冒，性能足以撑到下一次升级
